#!/bin/sh

while [ -f $HOME/.VRlock ]
do
		filename="$HOME/tlf/soundlogs/"`eval date +%d%H%M`".au"
		if test -f $filename
		then
			sleep 10
		else
			# Example command for OSS rec
			# rec -w  -r 8000 $filename > /dev/null 2> /dev/null

			# Example command for SoX rec
			rec -c 1  -r 8000 -q $filename
		fi
done
