#!/bin/sh

#
# check that all rules are included in the distribution archive
#

eval "$(grep PACKAGE_VERSION= configure)"

TARGZ=tlf-${PACKAGE_VERSION}.tar.gz

echo
echo Checking rules in distribution archive $TARGZ
echo

#
# extract the list of files in the rules directory, excluding Makefiles
#
tar tzf $TARGZ \
    | grep /rules/ \
    | grep -v '/$' \
    | sed -e 's:^tlf.\+/rules:rules:' \
    | grep -v Makefile \
    | sort > rules_dist

#
# see what we have in the repo
#
find rules -type f \
    | grep -v Makefile \
    | sort > rules_repo

#
# diff them
#
diff -y --suppress-common-lines rules_repo rules_dist

if [ $? -ne 0 ]; then
    echo
    echo "---- Files marked with '<' are missing from RULES_FILES in rules/Makefile.am"
    echo
    rc=1
else
    echo
    echo "---- OK"
    echo
    rc=0
fi

exit $rc

